"""Derive reported ordinary-share face value without claiming event continuity."""
from datetime import datetime, timezone
from decimal import Decimal as D
from fractions import Fraction as F
from pathlib import Path
import json
from check_moutai_ttm_comparability import ROOT, sha, texts

def main():
    annual=ROOT/'runtime/strategy-validation/moutai-warmup-20260909T062823719664Z/annual-inputs.json'
    if sha(annual)!='41f7d1fb196adc6840ea43bb58ddf57a38116334410a4ee61b589ac4bfc231fc':
        raise ValueError('Annual point-in-time evidence changed')
    row=next(r for r in json.loads(annual.read_text(encoding='utf-8')) if r['report_year']==2013)
    pdf=ROOT/row['source_path']
    if sha(pdf)!=row['raw_file_hash'] or sha(ROOT/row['index_path'])!=row['index_hash']:
        raise ValueError('Original report or publication index changed')
    checks={27:['单位：股','1、人民币普通股1,038,180,0001001,038,180,000100',
                '三、股份总数1,038,180,0001001,038,180,000100'],
            45:['实收资本（或股本）（二十六）1,038,180,000.001,038,180,000.00'],
            55:['单位:元币种:人民币','一、上年年末余额1,038,180,000.00']}
    for page,phrases in checks.items():
        pair=texts(pdf,page)
        for phrase in phrases:
            if any(phrase not in t for t in pair):
                raise ValueError('Share/capital basis mismatch '+str(page)+' '+phrase)
    capital=D('1038180000.00'); shares=D('1038180000')
    face=capital/shares
    if F(face)!=F(capital)/F(shares) or str(row['inputs']['ending_issued_shares'])!=str(int(shares)):
        raise ValueError('Independent face-value derivation failed')
    if row['available_at']>='2015-01-01T00:00:00+08:00' or not row['availability_bound_verified']:
        raise ValueError('Future or unverified publication information')
    out=ROOT/'runtime/strategy-validation'/('moutai-face-value-'+datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ'))
    out.mkdir()
    result={'symbol':'600519','source_id':row['source_id'],'source_url':row['source_url'],
        'source_path':row['source_path'],'source_sha256':row['raw_file_hash'],
        'publication_index_path':row['index_path'],'publication_index_sha256':row['index_hash'],
        'report_period_end':'2013-12-31','available_at':row['available_at'],
        'availability_method':row['availability_method'],'original_page_checks':checks,
        'issued_ordinary_shares':str(shares),'paid_in_share_capital_cny':str(capital),
        'derived_cny_per_ordinary_share':str(face),'derivation':'paid_in_share_capital_cny / issued_ordinary_shares',
        'independent_fraction_check':'passed','full_2015_fee_inputs_approved':False,
        'limits':['Derived same-report face-value basis, not a direct charter quotation.',
            'Does not establish absence of later denomination/split changes through July 2015.',
            'Broker-retained fee/minimum and rounding remain explicit research assumptions, not historical account facts.',
            'No trade or strategy return generated by this evidence check.']}
    (out/'evidence.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
    (out/'manifest.json').write_text(json.dumps({'script_sha256':sha(Path(__file__)),
        'evidence_sha256':sha(out/'evidence.json')},indent=2),encoding='utf-8')
    print(json.dumps({'output':str(out),'face_value':str(face),'available_at':row['available_at']}))

if __name__=='__main__':
    main()
